# Generated by Django 4.1.3 on 2023-02-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproductindustry',
            name='Domain_Server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
