# Generated by Django 4.1.3 on 2023-02-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_listproductindustry_domain_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproductindustry',
            name='Oder_Image',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
